extends: default
ignore:
  - fulfillment-service/charts/*/templates/
  - fulfillment-service/it/charts/*/templates/
  - osac-operator/charts/*/templates/
  - osac-operator/config/
rules:
  line-length: disable
  document-start: disable
  indentation:
    indent-sequences: whatever
  hyphens:
    max-spaces-after: 4
  truthy:
    check-keys: false
